### PR TITLE
Config

### PR DESCRIPTION
**Pull request by mosemister**

### CODE REVIEW

**Review by ColonelKai — APPROVED** [review]
Looks good, but should we separate the list of config values to a separate file as not to clutter the config class?

**Comment by mosemister** [comment]
> Looks good, but should we separate the list of config values to a separate file as not to clutter the config class?

Can do. However that then creates a class dependency structure where classes rely on eachother.

But im fine to ignore that standard for a ``ConfigNodes`` class

**Comment by ColonelKai** [comment]
Alright. Sounds good. Please make the change, then we can merge

**Comment by mosemister** [comment]
> Alright. Sounds good. Please make the change, then we can merge

Updated

**Pull request merged**
